name: 'StackHawk HawkScan Action'
description: 'Find security bugs in your application with HawkScan DAST'
author: 'Zachary Conger'

inputs:
  apiKey:
    description: StackHawk API key
    required: true
  dryRun:
    description: If set to `true`, show HawkScan commands, but don't run them
    required: false
    default: false
  configurationFiles:
    description: Space-separated list of HawkScan configuration files to use
    required: false
    default: stackhawk.yml
  codeScanningAlerts:
    description: If `true`, Register a Code Scanning Alert in GitHub if scan alerts exceed `hawk.failureThreshold`
    required: false
    default: false
  githubToken:
    description: GitHub Token for uploading Code Scanning Alert info - required if `codeScanningAlerts` is enabled
    required: false
    default: ${{ github.token }}}
  installCLIOnly:
    description: If `true` the action will only install the CLI and not run a scan
    required: false
  default: false
  sourceURL:
    description: Source for ZIP file
    required: false
    default: https://download.stackhawk.com/hawk/cli
  version:
    description: HawkScan CLI version to use
    required: false
    default: latest

runs:
  using: node12
  main: dist/index.js

branding:
  icon: 'octagon'
  color: 'green'
