hawk:
  spider:
    maxDurationMinutes: 2
  failureThreshold: low
app:
  applicationId: ${APPLICATION_ID:test-app-id}
  env: ${ENV:Action Test}
  host: ${APP_HOST:https://localhost:9000}
  openApiConf:
    filePath: openapi.yaml
  authentication:
    loggedInIndicator: "\\QSign Out\\E"
    loggedOutIndicator: ".*Location:.*/login.*"
    usernamePassword:
      type: JSON
      loginPath: /api/jwt/auth/signin
      usernameField: username
      passwordField: password
      scanUsername: "user"
      scanPassword: "password"
    tokenAuthorization:
      type: HEADER
      value: Authorization
      tokenType: Bearer
    tokenExtraction:
      type: TOKEN_PATH
      value: "token"
    testPath:
      path: /api/jwt/items/search/i
      success: ".*200.*"
  autoPolicy: true
  autoInputVectors: true